# This workflow is meant to be a non-maintenance way to sync code signing files for all apps in the company. 
# Run this after creating a new iOS app to create code signing files for the app, for example. 
name: Create iOS code signing files 

on: 
  workflow_dispatch: # manually run the action from GitHub website

# Secrets required on github repository to run this workflow. 
# View CI_SETUP.md doc on how to find the values for these secrets. 
env:
  GOOGLE_CLOUD_MATCH_WRITE_SERVICE_ACCOUNT_B64: ${{ secrets.GOOGLE_CLOUD_MATCH_WRITE_SERVICE_ACCOUNT_B64 }}  
  APP_STORE_CONNECT_API_KEY_CONTENT_B64: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT_B64 }}

jobs:
  create-code-signing-files:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Fastlane (via ruby and Bundler) used for managing code signing files 
      uses: ruby/setup-ruby@e5ac7b085f6e63d49c8973eb0c6e04d876b881f1 # v1.230.0
      with:
        ruby-version: '3.0' 
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        
    - name: Create code signing files for all iOS apps 
      # runs function inside of fastlane/Fastfile      
      run: bundle exec fastlane create_all_code_signing_files
    